/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kpc.drugstore.gui;

import br.com.kpc.drugstore.core.Client;
import br.com.kpc.drugstore.core.IRepositoryClient;
import br.com.kpc.drugstore.dao.DaoClient;
import br.com.kpc.drugstore.service.Service;
import br.com.kpc.drugstore.tableModel.TableModelClient;
import br.com.kpc.drugstore.util.ApiSms;
import br.com.kpc.drugstore.util.FixedLengthDocument;
import br.com.kpc.drugstore.util.Mask;
import br.com.kpc.drugstore.util.SystemMessage;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author www
 */
public class Birthdays extends javax.swing.JFrame {

    /**
     * Creates new form AniversariantesDia
     */
    public Birthdays() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 153, 153));
        carregarCliente();
        taMensagem.setDocument(new FixedLengthDocument(140));
        lQtdEnviado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTotalRegistros = new javax.swing.JLabel();
        btSMS = new javax.swing.JButton();
        pbEnviando = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGrid = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensagem = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lQtdEnviado = new javax.swing.JLabel();
        lTotalCaracter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SMS Aniversariantes");

        lTotalRegistros.setText("Total de 0000 Clientes");

        btSMS.setText("Enviar SMS");
        btSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSMSActionPerformed(evt);
            }
        });

        tbGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbGrid);

        taMensagem.setColumns(20);
        taMensagem.setLineWrap(true);
        taMensagem.setRows(4);
        taMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taMensagemKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(taMensagem);

        jLabel2.setText("Insira o texto desejado, com até 150 caracteres e sem acentos e/ou cedilha, no campo “Mensagem”");

        lQtdEnviado.setText("Foram enviados xx de xx.");

        lTotalCaracter.setText("0 de 140");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTotalRegistros)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pbEnviando, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lTotalCaracter)
                                    .addComponent(lQtdEnviado))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTotalRegistros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lTotalCaracter)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbEnviando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lQtdEnviado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Client client;
    private TableModelClient model;
    //Criando uma lista de cliente
    private List<Client> listClientes = new ArrayList<Client>();
    // Define uma Thread para simular rodando  
    private Thread roda;

    private void btSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSMSActionPerformed
    
        // Inicia o processo  
        if (roda == null) {
            roda = new roda();
            roda.start();
        }


    }//GEN-LAST:event_btSMSActionPerformed

    private void taMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taMensagemKeyReleased

        lTotalCaracter.setText(taMensagem.getCaretPosition() +" de 140");
        
    }//GEN-LAST:event_taMensagemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Birthdays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Birthdays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSMS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lQtdEnviado;
    private javax.swing.JLabel lTotalCaracter;
    private javax.swing.JLabel lTotalRegistros;
    private javax.swing.JProgressBar pbEnviando;
    private javax.swing.JTextArea taMensagem;
    private javax.swing.JTable tbGrid;
    // End of variables declaration//GEN-END:variables

    private void carregarCliente() {
        //Carregando lista de client By Birthday
        listClientes = Service.getIRepositoryClient().listClientByBirthday();

        lTotalRegistros.setText("Total Registros: " + listClientes.size());

        model = new TableModelClient(listClientes);
        tbGrid.setModel(model);

    }

    private class roda extends Thread {

        public void run() {
            // Cria um objeto para atualizar a Barra  
            Runnable runner = new Runnable() {
                public void run() {
                    // Obtém o resultado atual da Barra  
                    int valor = pbEnviando.getValue();
                    // Atualiza a Barra  
                    pbEnviando.setValue(valor + 1);
                }
            };

            pbEnviando.setMaximum(listClientes.size());
            pbEnviando.setValue(0);

            //Passando o tamanho da lista
            int total = listClientes.size();
            int i = 0;
            String[] nomeCliente; 
            lQtdEnviado.setVisible(true);

            btSMS.setEnabled(false);
            for (Client c : listClientes) {
                //Validando se tem numero de celular
                if (c.getCellPhone_1() == "") {
                    if (c.getCellPhone_2() == "") {
                        SystemMessage.kpcShowMessage(null, SystemMessage.WARNING, "Não foi encontrado numero.");
                        return;
                    }
                }
                i++;
                pbEnviando.setValue(i);
                lQtdEnviado.setText("Foram enviados " + i + " de " + total + ".");
                nomeCliente = c.getName().split(" ");
                
                try {
                    ApiSms.simple(Mask.limparMasTelefone(c.getCellPhone_1()),nomeCliente[0] +", "+ taMensagem.getText().trim());
                } catch (Exception ex) {
                    Logger.getLogger(Birthdays.class.getName()).log(Level.SEVERE, null, ex);
                }
                  


                // Atualiza a Barra de Progresso  
                try {
                    SwingUtilities.invokeAndWait(runner);
                } catch (java.lang.reflect.InvocationTargetException e) {
                    break;
                } catch (InterruptedException e) {
                }
            }
            btSMS.setEnabled(true);

            roda = null;
        }
    }
}
